server:
  port: 8771

spring:
  ai:
    openai:
      base-url: http://127.0.0.1:8771
      api-key: sk-plI5Vzs4AQWWJkDT29Af517d624a4d48Ac9fA75589Ee30Fd
      chat:
        options:
          model: gpt-4.1-mini
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    # 个人配置，通过 http://127.0.0.1:8090 代理出去
    agent:
      base-url: https://apis.itedus.cn
      api-key: sk-plI5Vzs4AQWWJkDT29Af517d624a4d48Ac9fA75589Ee30Fd

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml