server:
  port: 8701

# http://localhost:8701/api/mcp
spring:
  config:
    activate:
      on-profile: stateless
  main:
    web-application-type: servlet # 启用Web
  ai:
    mcp:
      server:
        protocol: STATELESS
        stateless:
          mcp-endpoint: /api/mcp

logging:
  file:
    name: data/log/${spring.application.name}.log